#!/bin/bash

usage() {
    exit 1
    echo "Usage: autostart [start|stop|start-gaming|stop-gaming]"
}

# Get value of argument (action: start|stop|start-gaming|stop-gaming)
action=$1

if [ "$action" == "start" -o "$action" == "stop-gaming" ]; then
    hyprctl dispatch exec waybar &
    hyprctl dispatch exec hyprpaper &
    hyprctl dispatch exec hypridle &

    if [ "$action" == "start" ]; then
        vesktop --start-minimized &
		keepassxc &
    fi
elif [ "$action" == "stop" -o "$action" == "start-gaming" ]; then
    killall waybar
    killall hyprpaper
    killall hypridle

    if [ "$action" == "stop" ]; then
        # Since vesktop process is not named vesktop or anything related to it
        # (it's named electron), we need to find the pid of the vesktop process
        # by looking for the pid of the process with class "vesktop" using hyprctl
        pid=$(hyprctl clients | awk '/class: vesktop/{flag=1;next}/pid:/{if(flag){print $2;exit}}')

        # Kill vesktop if it is running
        if [ -n "$pid" ]; then
            kill $pid
        fi
    fi
else
    echo "Invalid action: $action"
    usage
fi
