#!/bin/bash

# Toggle bluetooth on/off
rfkill toggle bluetooth

# Get the current status of bluetooth and send a notification
if [ "$(rfkill list bluetooth | grep -o "Soft blocked: yes")" ]; then
    notify-send -i /usr/share/icons/hicolor/64x64/status/blueman-disabled.png "Bluetooth" "Bluetooth is now off"
else
    notify-send -i /usr/share/icons/hicolor/64x64/apps/blueman.png "Bluetooth" "Bluetooth is now on"
fi
