#!/bin/bash

usage() {
    echo "Usage: brightness [up|down]"
    exit 1
}

# Get value of argument (action: up, down)
action=$1

if [ -z "$action" ]; then
    usage
fi

MAX_BRIGHTNESS=$(brightnessctl | grep -oP 'Max brightness: \K\d+')
CURRENT_BRIGHTNESS=$(brightnessctl | grep -oP 'Current brightness: \K\d+')

if [ "$action" == "up" ]; then
    # Check if current brightness is already at max
    if [ "$CURRENT_BRIGHTNESS" -ge "$MAX_BRIGHTNESS" ]; then
        exit 1
    fi

    brightnessctl s +5%
   	#notify-send -i /usr/share/icons/AdwaitaLegacy/48x48/legacy/video-display.png "Monitor" "Brightness increased $(brightnessctl | grep -oP '\(\d+%\)')"
elif [ "$action" == "down" ]; then
    # Check if current brightness is already at 0 (minimum)
    if [ "$CURRENT_BRIGHTNESS" -le 0 ]; then
        exit 1
    fi

    brightnessctl s 5%-
    #notify-send -i /usr/share/icons/AdwaitaLegacy/48x48/legacy/video-display.png "Monitor" "Brightness decreased $(brightnessctl | grep -oP '\(\d+%\)')"
else
    echo "Invalid action: $action"
    usage
fi
