#!/bin/bash

usage() {
    echo "Usage: clip [history|clear]"
    exit 1
}

TERMINAL="kitty"

# Get value of argument (action: history, clear)
action=$1

if [ -z "$action" ]; then
    usage
fi

if [ "$action" == "history" ]; then
    # cliphist list | rofi -dmenu -p "Clipboard" -i -theme "$HOME/.config/rofi/clip.rasi"| cliphist decode | wl-copy
    $TERMINAL --class clipse -e 'clipse'
elif [ "$action" == "clear" ]; then
    clipse -clear
    notify-send -i /usr/share/icons/AdwaitaLegacy/48x48/legacy/edit-clear-all.png "Clipboard" "Clipboard history has been cleared."
else
    echo "Invalid action: $action"
    usage
fi
