#!/usr/bin/env sh
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '1p' | awk '{print $2}')

# Hyprland performance
if [ $HYPRGAMEMODE = 1 ]; then
	killall waybar
        killall hyprpaper
        killall hypridle
	hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:drop_shadow 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
        # notify-send "Gamemode" "Gamemode enabled"
else
	hyprctl reload
	waybar >/dev/null 2>&1 &
        hyprpaper >/dev/null 2>&1 &
        hypridle >/dev/null 2>&1 &
        # notify-send "Gamemode" "Gamemode disabled"
fi
