#!/bin/bash
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '1p' | awk '{print $2}')

# Hyprland performance
if [ $HYPRGAMEMODE = 1 ]; then
    # Load hyprland plugins (cs resolution fix)
    # hyprpm reload -n

    ~/.config/hypr/scripts/autostart start-gaming

	hyprctl --batch "\
	    keyword animations:enabled 0;\
	    keyword decoration:drop_shadow 0;\
	    keyword decoration:blur:enabled 0;\
	    keyword general:gaps_in 0;\
	    keyword general:gaps_out 0;\
	    keyword general:border_size 0;\
	    keyword decoration:rounding 0"

    hyprctl notify -1 2000 "rgb(26ff00)" "fontsize:25 Game mode enabled"
else
    hyprctl reload
    ~/.config/hypr/scripts/autostart stop-gaming
    hyprctl notify -1 2000 "rgb(ff0000)" "fontsize:25 Game mode disabled"
fi
