#!/bin/bash

# Check if there's a process running called hypridle
process_pid=$(pidof hypridle)

if [ -n "$process_pid" ]; then
    echo "hypridle is running, killing it"
    kill $process_pid
else
    echo "hypridle is not running, starting it"
    hypridle &
fi
