#!/bin/bash

usage() {
    echo "Usage: mediaplayer [play-pause|next|previous]"
    exit 1
}

# Get value of argument (action: play-pause|next|previous)
action=$1

if [ -z "$action" ]; then
    usage
fi

if [ "$action" == "play-pause" ]; then
    playerctl play-pause
    hyprctl notify -1 2500 "rgb(D9BE8E)" "fontsize:20 Music/Video has been toggled"
elif [ "$action" == "next" ]; then
    playerctl next
    hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:20 Next track"
elif [ "$action" == "previous" ]; then
    playerctl previous
    hypctl notify -1 2000 "rgb(D9BE8E)" "fontsize:20 Previous track"
else
    echo "Invalid action: $action"
    usage
    exit 1
fi

# Dismiss previous notifications
hyprctl dismissnotify

# Send notification
if [ "$action" == "play-pause" ]; then
    status=$(playerctl status)

    if [ "$status" == "Playing" ]; then
        hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 ▶️ Media: Playing"
    else
        hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 ⏸️ Media: Paused"
    fi
elif [ "$action" == "next" ]; then
    hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 ⏭️ Next track $(playerctl metadata title)"
elif [ "$action" == "previous" ]; then
    hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 ⏮️ Previous track $(playerctl metadata title)"
fi
