#!/bin/bash

sleep 4
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal
sleep 4

libDir=/usr/lib

$libDir/xdg-desktop-portal-hyprland &
$libDir/xdg-desktop-portal-gtk &
$libDir/xdg-desktop-portal &
