#!/usr/bin/env bash

sleep 4
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
sleep 4

# Use different directory on NixOS
if [ -d /run/current-system/sw/libexec ]; then
    libDir=/run/current-system/sw/libexec
else
    libDir=/usr/lib
fi

$libDir/xdg-desktop-portal-hyprland &
sleep 4
$libDir/xdg-desktop-portal &
