#!/bin/bash

sleep 5

# Run yay to check for updates and store the output
update_count=$(yay -Qu 2>/dev/null | wc -l)

# If the output is empty, set the count to 0
if [ "$update_count" -eq 0 ]; then
    update_count=0
fi

# Send a desktop notification with the number of updates
if [ "$update_count" -gt 0 ]; then
    notify-send -i /usr/share/icons/AdwaitaLegacy/48x48/legacy/emblem-default.png "System Updates" "$update_count updates are available."
    #node ~/Repos/Text-to-Speech/src/main.js "There are $update_count system updates available." "updates" "deleteAfterPlay"
else
    notify-send -i /usr/share/icons/AdwaitaLegacy/48x48/legacy/emblem-default.png "System Updates" "Your system is up to date."
fi
