#!/bin/bash

usage() {
    echo "Usage: volume [up|down|toggle-mute]"
    exit 1
}

# Get value of argument (action: up, down, toggle-mute)
action=$1

if [ -z "$action" ]; then
    usage
fi

# Function to get the current volume as a percentage
get_volume_percentage() {
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
    echo "$(awk -v vol="$volume" 'BEGIN { printf("%.0f", vol * 100) }')%"
}

get_volume_state() {
    # Check if it has the word "MUTED" in the output
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    if [[ $volume == *"MUTED"* ]]; then
        echo "Muted"
    else
        echo "Unmuted"
    fi
}

if [ "$action" == "up" ]; then
    wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 1%+
elif [ "$action" == "down" ]; then
    wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 1%-
elif [ "$action" == "toggle-mute" ]; then
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
else
    echo "Invalid action: $action"
    usage
    exit 1
fi

# Dismiss previous notifications
hyprctl dismissnotify

# Send notification
if [ "$action" == "toggle-mute" ]; then
    status=$(get_volume_state)

    if [ "$status" == "Muted" ]; then
        hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 🔇 Volume: $(get_volume_state)"
    else
        hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 🔊 Volume: $(get_volume_state)"
    fi
else
    hyprctl notify -1 2000 "rgb(D9BE8E)" "fontsize:30 🎵 Volume: $(get_volume_percentage)"
fi
