#!/bin/bash

usage() {
    echo "Usage: volume [up|down|toggle-mute]"
    exit 1
}

# Get value of argument (action: up, down, toggle-mute)
action=$1

if [ -z "$action" ]; then
    usage
fi

# Function to get the current volume as a percentage
get_volume_percentage() {
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
    echo "$(awk -v vol="$volume" 'BEGIN { printf("%.0f", vol * 100) }')%"
}

if [ "$action" == "up" ]; then
    wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
elif [ "$action" == "down" ]; then
    wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-
elif [ "$action" == "toggle-mute" ]; then
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
else
    echo "Invalid action: $action"
    usage
fi
