import = [
	"~./config/alacritty/themes/gruvbox_dark.toml"
]

[window]

opacity = 0.9

dimensions.lines = 45
dimensions.columns = 120

padding.x = 10
padding.y = 10

decorations = "Full"
# decorations = "None"
# decorations_theme_variant = "Dark" | "Light"

dynamic_title = true

[font]

#normal.family = "MesloLGS NF"
normal.family = "CaskaydiaCove Nerd Font Mono"
bold.family = "CaskaydiaCove Nerd Font Mono"
italic.family = "CaskaydiaCove Nerd Font Mono"
bold_italic.family = "CaskaydiaCove Nerd Font Mono"

size = 12.0

